// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Global: typeof import('./src/components/common/global.vue')['default']
    GlobalDialog: typeof import('./src/components/common/GlobalDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/common/Message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  }
}
